// <auto-generated />
namespace _TrashCollector_DCC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialandUserrolles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialandUserrolles));
        
        string IMigrationMetadata.Id
        {
            get { return "201812130204264_Initial and User rolles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
